

DROP TABLE IF EXISTS local;
DROP TABLE IF EXISTS international;
DROP TABLE IF EXISTS ANALYST_WORK_LABORATORY;
DROP TABLE IF EXISTS EQUIPMENT_COMPANY_ANALYSIS;
DROP TABLE IF EXISTS cash;
DROP TABLE IF EXISTS credit;
DROP TABLE IF EXISTS sale;
DROP TABLE IF EXISTS Management;
DROP TABLE IF EXISTS Purchases;
DROP TABLE IF EXISTS Technical;
DROP TABLE IF EXISTS CLIENT_COMPANY_Works_Client_CONTACT;
DROP TABLE IF EXISTS EQUIPMENT_COMPANY_TECHNICAL_PROBLEMS;
DROP TABLE IF EXISTS EQUIPMENT_COMPANY_PRODUCT_CONCENTRATION_DOSSAGE;
DROP TABLE IF EXISTS EQUIPMENT_COMPANY;
DROP TABLE IF EXISTS Consultant_Works_Analyst_Company;
DROP TABLE IF EXISTS Well;
DROP TABLE IF EXISTS Fuel;
DROP TABLE IF EXISTS Steam;
DROP TABLE IF EXISTS softener;
DROP TABLE IF EXISTS Condensate_pipe;
DROP TABLE IF EXISTS Boiler_Feed;
DROP TABLE IF EXISTS Boiler;
DROP TABLE IF EXISTS ANALYSIS;
DROP TABLE IF EXISTS TECHNICAL_PROBLEMS;
DROP TABLE IF EXISTS Cycle_Type;
DROP TABLE IF EXISTS Manufacturing_Equipment;
DROP TABLE IF EXISTS Equipment;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS CLIENT_COMPANY;
DROP TABLE IF EXISTS ANALYST;
DROP TABLE IF EXISTS LABORATORY;
DROP TABLE IF EXISTS CLIENT_CONTACT;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS Analyst_Company;
DROP TABLE IF EXISTS CONSULTANT;
SET FOREIGN_KEY_CHECKS=1;



CREATE TABLE Equipment (
	id_equipment VARCHAR(50) NOT NULL,
	equipment_description VARCHAR(50),
	equipment VARCHAR(50),
	PRIMARY KEY (id_equipment)
	);

CREATE TABLE Manufacturing_Equipment (	
	id_manufacturer VARCHAR(50) NOT NULL,
	manufacturer VARCHAR(50),
	PRIMARY KEY (id_manufacturer)
	);

CREATE TABLE Cycle_Type (
	id_cycle_type VARCHAR(50) NOT NULL,
	cycle_type VARCHAR(50),
	PRIMARY KEY (id_cycle_type)
	);

CREATE TABLE CONSULTANT (
    ID_CONSULTANT VARCHAR(255),
    SURNAME VARCHAR(255),
    FAMILY_NAME VARCHAR(255),
    AREA_OF_SPECIALTY VARCHAR(255),
    PRIMARY KEY(ID_CONSULTANT)
	);

CREATE TABLE Analyst_Company (
	id_analyst_company VARCHAR(50) NOT NULL,
	country VARCHAR(50),
	PRIMARY KEY (id_analyst_company)
	);

CREATE TABLE PRODUCTS (
    ID_PRODUCT VARCHAR(255),
    FORMULA VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY(ID_PRODUCT)
);

CREATE TABLE TECHNICAL_PROBLEMS (
    ID_TECHNICAL_PROBLEMS VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255),
    FOTO_EXAMPLE VARCHAR(255),
    PRIMARY KEY(ID_TECHNICAL_PROBLEMS)
);

CREATE TABLE CLIENT_CONTACT (
    ID_CONTACT VARCHAR(255),
    SURNAME VARCHAR(255),
    FAMILY_NAME VARCHAR(255),
    ROLE VARCHAR(255),
    TELEPHONE_NUMBER INT NOT NULL,
    EMAIL_ADDRESS VARCHAR(255),
	date_birth VARCHAR(50),
    PRIMARY KEY(ID_CONTACT)
	);

CREATE TABLE LABORATORY (
    ID_LABORATORY VARCHAR(255),
    NAME_LABORATORY VARCHAR(255),
    TELEPHONE INT NOT NULL,
    EMAIL VARCHAR(255),
    CONTACT_SURNAME VARCHAR(255),
    CONTACT_FAMILYNAME VARCHAR(255),
    COUNTRY VARCHAR(255),
    PRIMARY KEY(ID_LABORATORY)
	);
    
 CREATE TABLE ANALYST (
    ID_ANALYST VARCHAR(255),
    SURNAME VARCHAR(255),
    FAMILY_NAME VARCHAR(255),
    GENDER VARCHAR(255),
    PRIMARY KEY(ID_ANALYST)
	);

CREATE TABLE ANALYSIS (
    ID_ANALYSIS VARCHAR(255),
    ANALYSIS VARCHAR(255),
    ANALYSIS_METHOD_DESCRIPTION VARCHAR(255),
    PRIMARY KEY(ID_ANALYSIS)
	);
    
  CREATE TABLE CLIENT_COMPANY (
    ID_CLIENT_COMPANY VARCHAR(255),
    NAME VARCHAR(255),
    COUNTRY VARCHAR(255),
    PLANT_NAME VARCHAR(255),
    PRIMARY KEY(ID_CLIENT_COMPANY)
	);  

CREATE TABLE Boiler (
	id_equipment VARCHAR(50) NOT NULL,
	potency VARCHAR(50),
	pipe_type VARCHAR(50),
	PRIMARY KEY (id_equipment),
	FOREIGN KEY (id_equipment) REFERENCES Equipment(id_equipment) ON DELETE CASCADE);

CREATE TABLE Boiler_Feed (
	id_equipment VARCHAR(50) NOT NULL,
	pipe_diameter VARCHAR(50),
	PRIMARY KEY (id_equipment),
	FOREIGN KEY (id_equipment) REFERENCES Equipment(id_equipment) ON DELETE CASCADE);
	
CREATE TABLE Condensate_pipe (
	id_equipment VARCHAR(50) NOT NULL,
	pipe_length VARCHAR(50),
	pipe_diameter VARCHAR(50),
	PRIMARY KEY (id_equipment),
	FOREIGN KEY (id_equipment) REFERENCES Equipment(id_equipment) ON DELETE CASCADE);
	
CREATE TABLE softener (
	id_equipment VARCHAR(50) NOT NULL,
	softener_type VARCHAR(50),
	PRIMARY KEY (id_equipment),
	FOREIGN KEY (id_equipment) REFERENCES Equipment(id_equipment) ON DELETE CASCADE);
	
CREATE TABLE Steam (
	id_cycle_type VARCHAR(50) NOT NULL,
	Pressure VARCHAR(50),
	PRIMARY KEY (id_cycle_type),
	FOREIGN KEY (id_cycle_type) REFERENCES Cycle_Type(id_cycle_type) ON DELETE CASCADE);

CREATE TABLE Fuel (
	id_cycle_type VARCHAR(50) NOT NULL,
	fuel_type VARCHAR(50),
	PRIMARY KEY (id_cycle_type),
	FOREIGN KEY (id_cycle_type) REFERENCES Cycle_Type(id_cycle_type) ON DELETE CASCADE);

CREATE TABLE Well (
	id_cycle_type VARCHAR(50) NOT NULL,
	Well_type VARCHAR(50),
	PRIMARY KEY (id_cycle_type),
	FOREIGN KEY (id_cycle_type) REFERENCES Cycle_Type(id_cycle_type) ON DELETE CASCADE);


CREATE TABLE Consultant_Works_Analyst_Company (
	since VARCHAR(50) NOT NULL,
	until VARCHAR(50),
	status VARCHAR(50),
	id_analyst_company VARCHAR(50),
	ID_CONSULTANT VARCHAR(50),
	PRIMARY KEY (since),
	FOREIGN KEY (id_analyst_company) REFERENCES Analyst_Company(id_analyst_company),
	FOREIGN KEY (ID_CONSULTANT) REFERENCES CONSULTANT(ID_CONSULTANT)
	);	

CREATE TABLE EQUIPMENT_COMPANY(
    YEAR_OF_MANUFACTURING DATE,
    YEAR_OF_INSTALLATION DATE,
    id_equipment VARCHAR(255),
    EQUIPMENT VARCHAR(255),
    id_manufacturer VARCHAR(255),
    MANUFACTURER VARCHAR(255),
    id_cycle_type VARCHAR(255),
	CYCLE_TYPE VARCHAR(255),
    ID_CLIENT_COMPANY VARCHAR(255),
    SEQUENTIAL VARCHAR(255),   
    PRIMARY KEY (SEQUENTIAL),
	FOREIGN KEY (id_equipment) REFERENCES Equipment (id_equipment),
    FOREIGN KEY (id_manufacturer) REFERENCES Manufacturing_Equipment (id_manufacturer),
    FOREIGN KEY (id_cycle_type) REFERENCES Cycle_Type (id_cycle_type),
    FOREIGN KEY (ID_CLIENT_COMPANY) REFERENCES CLIENT_COMPANY (ID_CLIENT_COMPANY)
	);
	
CREATE TABLE EQUIPMENT_COMPANY_PRODUCT_CONCENTRATION_DOSSAGE(
	ID_PRESCRIPTION VARCHAR(255),
    DETAIL_PERSCRIPTION VARCHAR(255),
    ID_PRODUCT VARCHAR(255),
    DATE_PERSCRIPTION DATE,
    DATE_START_USAGE DATE,
    DATE_END_USAGE DATE,
    SEQUENTIAL VARCHAR(255),
    ID_CONSULTANT VARCHAR(255),   
    PRIMARY KEY (ID_PRESCRIPTION),
	FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT),
    FOREIGN KEY (SEQUENTIAL) REFERENCES EQUIPMENT_COMPANY (SEQUENTIAL),
    FOREIGN KEY (ID_CONSULTANT) REFERENCES CONSULTANT (ID_CONSULTANT)
);	

CREATE TABLE EQUIPMENT_COMPANY_TECHNICAL_PROBLEMS(
	ID_PROBLEM VARCHAR(255),
    PROBLEM_DATE DATE,
    SEQUENTIAL VARCHAR(255),
    PROBLEM_DESCRIPTION VARCHAR(255),
    FOTO_SPECIFIC_PROBLEM VARCHAR(255),
    ID_TECHNICAL_PROBLEMS VARCHAR(255),
    ID_CONSULTANT VARCHAR(255),   
    PRIMARY KEY (ID_PROBLEM),
	FOREIGN KEY (ID_TECHNICAL_PROBLEMS) REFERENCES TECHNICAL_PROBLEMS (ID_TECHNICAL_PROBLEMS),
    FOREIGN KEY (SEQUENTIAL) REFERENCES EQUIPMENT_COMPANY (SEQUENTIAL),
    FOREIGN KEY (ID_CONSULTANT) REFERENCES CONSULTANT (ID_CONSULTANT)
);	
	


CREATE TABLE CLIENT_COMPANY_Works_Client_CONTACT(
	SINCE VARCHAR(255),
    UNTIL VARCHAR(255),
    STATUS VARCHAR(255),
    ID_CONTACT VARCHAR(255),
    ID_CLIENT_COMPANY VARCHAR(255),
	PRIMARY KEY (SINCE),
    FOREIGN KEY (ID_CONTACT) REFERENCES CLIENT_CONTACT (ID_CONTACT), 
    FOREIGN KEY (ID_CLIENT_COMPANY) REFERENCES CLIENT_COMPANY (ID_CLIENT_COMPANY)
	);	
	
CREATE TABLE Technical (
    ID_CONTACT VARCHAR(255),
    career VARCHAR(50),
    PRIMARY KEY(ID_CONTACT),
	FOREIGN KEY (ID_CONTACT) REFERENCES CLIENT_CONTACT (ID_CONTACT) ON DELETE CASCADE
	);
	
CREATE TABLE Purchases (
    ID_CONTACT VARCHAR(255),
	purchase_date DATE,
    PRIMARY KEY(ID_CONTACT),
	FOREIGN KEY (ID_CONTACT) REFERENCES CLIENT_CONTACT (ID_CONTACT) ON DELETE CASCADE
	);	
	
CREATE TABLE Management (
    ID_CONTACT VARCHAR(255),
    department VARCHAR(50),
    PRIMARY KEY(ID_CONTACT),
	FOREIGN KEY (ID_CONTACT) REFERENCES CLIENT_CONTACT (ID_CONTACT) ON DELETE CASCADE
	);	
	
CREATE TABLE Sale (
    invoice_number VARCHAR(50),
	id_client_company VARCHAR(50),
	sale_date DATE,
	id_product VARCHAR(50),
	formula VARCHAR(50),
	form_payment VARCHAR(50),
	quantity INTEGER (10),
	price INTEGER (10),
    PRIMARY KEY(invoice_number),
	FOREIGN KEY (id_client_company) REFERENCES CLIENT_COMPANY (ID_CLIENT_COMPANY),
	FOREIGN KEY (id_product) REFERENCES PRODUCTS (ID_PRODUCT)
	);	

CREATE TABLE credit (
    invoice_number VARCHAR(255),
    days_of_credit VARCHAR(50),
    PRIMARY KEY(invoice_number),
	FOREIGN KEY (invoice_number) REFERENCES Sale (invoice_number) ON DELETE CASCADE
	);	
	
CREATE TABLE cash (
    invoice_number VARCHAR(255),
    cash_amount VARCHAR(50),
    PRIMARY KEY(invoice_number),
	FOREIGN KEY (invoice_number) REFERENCES Sale (invoice_number) ON DELETE CASCADE
	);
	
CREATE TABLE EQUIPMENT_COMPANY_ANALYSIS(
	ID_analysis VARCHAR(255),
    DATE_OF_SAMPLE DATE,
    DATE_OF_ANALYSIS DATE,
    ID_ANALYST VARCHAR(255),
    ANALYSIS_VALUE varchar(255),
    SEQUENTIAL VARCHAR(255),
    ID_CONSULTANT VARCHAR(255),
	numeric_value_test VARCHAR(255),
    PRIMARY KEY (ID_analysis),
	FOREIGN KEY (ID_analysis) REFERENCES ANALYSIS (ID_analysis),
	FOREIGN KEY (ID_ANALYST) REFERENCES ANALYST (ID_ANALYST),
    FOREIGN KEY (SEQUENTIAL) REFERENCES EQUIPMENT_COMPANY (SEQUENTIAL),
    FOREIGN KEY (ID_CONSULTANT) REFERENCES CONSULTANT (ID_CONSULTANT)
);	
	
CREATE TABLE ANALYST_WORK_LABORATORY(
	SINCE VARCHAR(255),
    UNTIL VARCHAR(255),
    STATUS VARCHAR(255),
    ID_ANALYST VARCHAR(255),
    ID_LABORATORY VARCHAR(255),
    FOREIGN KEY (ID_ANALYST) REFERENCES ANALYST (ID_ANALYST), 
    FOREIGN KEY (ID_LABORATORY) REFERENCES LABORATORY (ID_LABORATORY)
);

CREATE TABLE international (
    ID_LABORATORY VARCHAR(255),
    speciality VARCHAR(50),
    PRIMARY KEY(ID_LABORATORY),
	FOREIGN KEY (ID_LABORATORY) REFERENCES LABORATORY (ID_LABORATORY) ON DELETE CASCADE
	);	
	
CREATE TABLE local (
    ID_LABORATORY VARCHAR(255),
    speciality VARCHAR(50),
    PRIMARY KEY(ID_LABORATORY),
	FOREIGN KEY (ID_LABORATORY) REFERENCES LABORATORY (ID_LABORATORY) ON DELETE CASCADE
	);
    

